# -*- coding: utf-8 -*-
"""PD_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15GobskL8eiwWyKTPJ8JptzY0eZ1f_Dwq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


co2_production = pd.read_csv ("/content/co2_production.csv")

"""**Цели устойчивого развития** (ЦУР) — это стратегия всего человечества для того, чтобы будущему поколению передать планету в хорошем состоянии и сформировать условия для развития общества, экономики и экологии.
Контроль выбросов углекислого газа в атмосферу земли является важным этапом в достижении устойчивого развития, т.к. этот показатель характеризует ответственное потребление и произодство.

Оценим полноту данных.
"""

import missingno as msno
msno.bar(co2_production)

"""Очистим данные от излишних и отсутствующих значений."""

co2_production.columns

CO2 = co2_production.dropna()
CO2.columns = [elem.replace('co2_prod_', '') for elem in CO2.columns]
CO2.shape

CO2_sum = CO2[['1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021']].sum()

"""Построим график суммарных выбросов с 1990 по 2021 гг. в мире в целом."""

plt.figure(figsize= (15,8))
sns.lineplot(CO2_sum, x = CO2_sum.index , y = CO2_sum, color = "green",
             marker='o',ms=10)
plt.grid(True)
plt.xticks(rotation = 45)

plt.title('Ежегодные мировые выбросы CO2 ', fontweight = 'bold')
plt.xlabel('Год',fontweight = 'bold')
plt.ylabel('Углекислый газ, тонн (CO2)', fontweight = 'bold')
plt.show()

"""Как видно из графика "Ежегодные мировые выбросы CO2", показатель "Углекисый газ" имеет тенденцию к росту. В отдельные года отмечается его снижение. Так например в 1997 году был принят Киотский протокол, заключённый с целью сокращения выбросов парниковых газов в атмосферу Земли для противодействия глобальному потеплению. А в 2008 году случился мировой финансовый кризис, к прямым последствиям которого также относятся - снижение объема производства.

Оценим количество стран с очень высокими выбросами углекислого газа в 2021 году.
"""

sns.histplot(CO2['2021'], color = "green")
plt.show()

"""Создадим новый датафрейм, отстортируем его по интересующему значению и заново проиндексируем его."""

High_CO2 = CO2[(CO2['hdicode'] == "Very High")].sort_values('2021',
                ascending=False).reset_index(drop=True)
High_CO2.head(5)

"""Исправим ошибку в названии страны."""

High_CO2.loc[14,'Country'] = 'Turkey'

"""Построим график для стран с максимальными выбросами CO2."""

plt.figure(figsize=(15, 8))
sns.barplot(y = High_CO2['Country'], x = High_CO2['2021'], palette = 'viridis')

plt.title('Страны с высокими выбросами CO2 (2021)', fontweight = 'bold')
plt.ylabel('Страны', fontweight = 'bold')
plt.xlabel('Выбросы CO2 в 2021', fontweight = 'bold')

plt.grid(True,axis = 'x')

plt.show()

"""В антирейтинг 2021 года вошли 24 страны, в том числе и Беларусь."""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

HDI = pd.read_csv("/content/human_development_index.csv")

"""**Индекс человеческого развития** (ИЧР) – это интегральный показатель, рассчитываемый для измерения средней продолжительности жизни, продолжительности обучения и валового национального дохода по паритету покупательной способности на душу населения на конкретной территории.
Показатели индекса человеческого развития отражают прогресс Республики Беларусь в достижении Целей устойчивого развития.

Оценим полноту данных.
"""

import missingno as msno
msno.bar(HDI)

"""Как видно из графика: до 2000 года много пропущенных значений, это может быть связано с тем, что в некоторых страннах не разрабатывали этот показатель.
Заменим Nan значения на нули.
"""

HDI = HDI.fillna(0)

"""Избавим названия колонок для лучшего восприятия от излишней информации."""

HDI.columns

HDI.columns = [elem.replace('hdi_', '') for elem in HDI.columns]

"""Так как в анализе используются индексы, логично расчитать их среднее значение по годам и построить на их основе график изменения ИЧР с 1990 по 2021 года."""

HDI_mean = HDI[['1990', '1991','1992', '1993', '1994', '1995', '1996', '1997',
                '1998', '1999', '2000','2001', '2002', '2003', '2004', '2005',
                '2006', '2007', '2008', '2009','2010', '2011', '2012', '2013',
                '2014', '2015', '2016', '2017', '2018','2019', '2020',
                '2021']].mean()

plt.figure(figsize= (15,8))
sns.lineplot(HDI_mean, x = HDI_mean.index , y = HDI_mean, color = "maroon",
             marker='o',ms=10)
plt.grid(True)
plt.xticks(rotation = 90)

plt.title('Среднее значение ИЧР за год в мире', fontweight = 'bold')
plt.xlabel('Год',fontweight = 'bold')
plt.ylabel('Среднее значение ИЧР', fontweight = 'bold')
plt.show()

"""Начиная с 1990 года наблюдается ежегодный прирост усредненного показателя ИЧР в целом в мире, за исключением его спада в 2020 году.

Оценим количество стран с очень высоким уровнем ИЧР в 2021 году.
"""

sns.histplot(HDI['2021'],color = "maroon")
plt.show()

"""Создадим новый датафрейм, отстортируем его по интересующему значению и заново проиндексируем его."""

High_HDI = HDI[(HDI['rank_2021'].between(1,10))].sort_values('2021',
              ascending=False).reset_index(drop=True)
High_HDI.head(10)

"""Построим график для десяти стран с наилучшим рейтингом ИЧР в 2021 году."""

plt.figure(figsize=(10, 5))
sns.barplot(y = High_HDI['Country'], x = High_HDI['2021'], palette = 'RdBu')

plt.title('Страны с высоким ИЧР(2021)', fontweight = 'bold')
plt.ylabel('Страны', fontweight = 'bold')
plt.xlabel('ИЧР в 2021', fontweight = 'bold')

plt.grid(True,axis = 'x')

plt.show()

"""Беларусь находится на 60 месте в рейтинге ИЧР за 2021 год.
Оценим положение Беларуси по сравнению по странами соседями: Россия, Украина, Польша, Латвия, Литва.

До 1995 года Беларусь не разрабатывала показатель ИЧР, поэтому рассмотри динамику показателя с 1995 по 2021 гг.
"""

HDI_2 = HDI.drop(columns = ["region","rank_2021","1990","1991","1992",
                            "1993","1994"])

BLR_hdi = HDI_2[HDI_2["Country"] == 'Belarus']
RUS_hdi = HDI_2[HDI_2["Country"] == 'Russian Federation']
UKR_hdi = HDI_2[HDI_2["Country"] == 'Ukraine']
PLN_hdi = HDI_2[HDI_2["Country"] == 'Poland']
LAT_hdi = HDI_2[HDI_2["Country"] == 'Latvia']
LIT_hdi = HDI_2[HDI_2["Country"] == 'Lithuania']

plt.figure(figsize=(12,8))
sns.pointplot(data = BLR_hdi, color = "red")
sns.pointplot(data = RUS_hdi, color = "orange")
sns.pointplot(data = UKR_hdi, color = "yellow")
sns.pointplot(data = PLN_hdi, color = "green")
sns.pointplot(data = LAT_hdi, color = "blue")
sns.pointplot(data = LIT_hdi, color = "purple")

plt.grid()
plt.xticks(rotation= 90)

plt.xlabel('Год',fontweight = 'bold')
plt.ylabel('ИЧР',fontweight = 'bold')
plt.title('Сравнение ИЧР с 1990 по 2021 между соседями Беларуси',fontweight = 'bold')

plt.show()

"""По графику можно сказать, что все рассматриваемые страны придерживаются общемировой тенденции на рост Индекса человеческого развития."""